something = input('Enter something: ')
print(f'Its primitive type is: {type(something)}')
print(f'Its alphanumeric? {something.isalnum()}')
print(f'Its alphabet? {something.isalpha()}')
print(f'Its decimal? {something.isdecimal()}')
print(f'Its a digit? {something.isdigit()}')
print(f'Its a identifier? {something.isidentifier()}')
print(f'Its lower? {something.islower()}')
print(f'Its numeric? {something.isnumeric()}')
print(f'Its printable? {something.isprintable()}')
print(f'Its a space? {something.isspace()}')
print(f'Its a title? {something.istitle()}')
print(f'Its uppercase? {something.isupper()}')

